{{cpp/title|unexpected}}
{{cpp/error/navbar}}
{{dcl begin}}
{{dcl header|exception}}
{{dcl rev begin}}
{{dcl|until=c++11|
void unexpected();
}}
{{dcl|deprecated=c++11|until=c++17|
[[noreturn]] void unexpected();
}}
{{dcl rev end}}
{{dcl end}}

C++ 运行时在违背[[cpp/language/except_spec|动态异常规定]]时调用 {{tt|std::unexpected()}}：从异常规定禁止某个类型异常的函数抛出了该类型的异常。

也可以从程序直接调用 {{tt|std::unexpected()}}。

两种情况下 {{tt|std::unexpected}} 都会调用当前安装的 {{lc|std::unexpected_handler}}。默认的 {{lc|std::unexpected_handler}} 会调用 {{lc|std::terminate}}。

{{rev begin}}
{{rev|until=c++11|
如果析构函数在栈回溯期间重置了非预期处理函数，且之后的回溯导致调用 {{tt|unexpected}}，那么会调用在 throw 表达式结尾安装的处理函数。（注意：重抛出是否应用新的处理函数是有歧义的）
}}
{{rev|since=c++11|
如果析构函数在栈回溯期间重置了非预期处理函数，那么之后的回溯导致调用 {{tt|unexpected}} 时调用哪个处理函数是未指定的。
}}
{{rev end}}

===异常===
抛出当前安装的 {{lc|std::unexpected_handler}} 抛出的异常。

===缺陷报告===
{{dr list begin}}
{{dr list item|wg=lwg|dr=2111|std=C++11|before=在栈回溯期间调用 {{lc|std::set_unexpected}} 的效果与 C++98 不同，并破坏一些 ABI|after=令它未指定}}
{{dr list end}}

===参阅===
{{dsc begin}}
{{dsc inc|cpp/utility/expected/dsc unexpected}}
{{dsc inc|cpp/error/dsc unexpected_handler}}
{{dsc end}}

{{langlinks|de|en|es|fr|it|ja|pt|ru}}