{{cpp/title|nested_exception}}
{{cpp/error/navbar}}
{{ddcl|header=exception|since=c++11|1=
class nested_exception;
}}

{{tt|std::nested_exception}} is a polymorphic mixin class which can capture and store the current exception, making it possible to nest exceptions of arbitrary types within each other.  

{{rrev|since=c++26|All member functions of {{tt|std::nested_exception}} are {{c/core|constexpr}}.}}

===Member functions===
{{dsc begin}}
{{dsc mem ctor|cpp/error/nested_exception/nested_exception|constructs a nested_exception}}
{{dsc mem vdtor|cpp/error/nested_exception/~nested_exception|destructs a nested exception}}
{{dsc mem fun|cpp/error/nested_exception/operator{{=}}|replaces the contents of a nested_exception}}
{{dsc mem fun|cpp/error/nested_exception/rethrow_nested|throws the stored exception}}
{{dsc mem fun|cpp/error/nested_exception/nested_ptr|obtains a pointer to the stored exception}}
{{dsc end}}

===Non-member functions===
{{dsc begin}}
{{dsc inc|cpp/error/dsc throw_with_nested}}
{{dsc inc|cpp/error/dsc rethrow_if_nested}}
{{dsc end}}

===Notes===
{{ftm begin}}
{{ftm|__cpp_lib_constexpr_exceptions|value=202411L|std=C++26|{{c/core|constexpr}} for exception types}}
{{ftm end}}

===Example===
{{include|cpp/error/example_nested_exception}}

===See also===
{{dsc begin}}
{{dsc inc|cpp/error/dsc exception_ptr}}
{{dsc inc|cpp/error/dsc throw_with_nested}}
{{dsc inc|cpp/error/dsc rethrow_if_nested}}
{{dsc end}}

{{langlinks|de|es|fr|it|ja|pt|ru|zh}}