{{cpp/title|bad_any_cast}}
{{cpp/utility/any/navbar}}
{{ddcl|header=any|since=c++17|
class bad_any_cast : public std::bad_cast;
}}

定义值返回形式的 {{lc|std::any_cast}} 在失败时抛出的对象的类型。

===成员函数===
{{cpp/error/exception/member of derived|bad_any_cast|std=c++17}}

{{inherited|[[cpp/types/bad_cast|{{small|std::}}bad_cast]]|}}

{{cpp/error/exception/inherit}}

===示例===
{{example
|code=
#include &lt;any&gt;
#include &lt;cassert&gt;
#include &lt;print&gt;

int main()
{
    auto x = std::any(42);
    assert(std::any_cast&lt;int&gt;(x) == 42); // OK

    try
    {
        [[maybe_unused]] auto s = std::any_cast&lt;std::string&gt;(x); // 抛出异常
    }
    catch (const std::bad_any_cast&amp; ex)
    {
        std::println("{}", ex.what());
    }
}
|p=true
|output=
bad any_cast
}}


{{langlinks|en|es|ja|ru}}